### ISSUE TITLE
Refine Distortion Key

### ISSUE THREAD

**Issue by Kelvinrr** [USGS-Astrogeology/ale#101]
Currently, the distortion model is defined by the name of the key. e.g. 

```
"optical_distortion" : {
    "radial" : {
    "coefficients" : [0,1,2,3]
     }
}
```

When we should be using a type key. 

```
"distortion_model"  : {
    "type" : "radial",
     "coefficients" : [0,1,2,3]
} 
```

**Comment by jessemapel** [comment]
This is a USGSCSM issue, see https://github.com/USGS-Astrogeology/usgscsm/issues/237
