### ISSUE TITLE
Drivers to Add

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/ale#106]
- [x] Cassini ISS - Kristin is on this.
- [ ] CaSSIS
- [ ] Galileo SSI
- [ ] HiRISE
- [ ] Mini-RF SAR

**Comment by Kelvinrr** [comment]
Cassini ISS already exists, but it's most likely broken (looks half implemented?) so if someone wants an easy one that's a good start.

**Comment by jessemapel** [comment]
Putting a hold on enhancements like this until after we re-architect.
