### ISSUE TITLE
Use of "Mission Name" for "Spacecraft name" in Pds3Label and elsewhere

### ISSUE THREAD

**Issue by kberryUSGS** [USGS-Astrogeology/ale#111]
In base.py, the `Pds3Label`  class has: 

```
@property
    def spacecraft_name(self):
        """
        Spacecraft name used in various Spice calls to acquire
        ephemeris data.

        Returns
        -------
        : str
          Spacecraft name
        """
        return self.label['MISSION_NAME']
```

Why is `MISSION_NAME` used for the spacecraft name? 

Also, in `config.py` there is a mixture of "spacecraft names" and "mission names" used for the metakernel path variable names.

**Comment by antonhibl** [comment]
This issue seems to have been addressed and can be closed, the relevant `Pds3Label` class is held in `label_pds3.py` and the spacecraft name is now returned as `SPACECRAFT_NAME` instead of `MISSION_NAME`.
