### ISSUE TITLE
Confusing terminology between image line/samp and detector line/samp

### ISSUE THREAD

**Issue by scsides** [USGS-Astrogeology/ale#115]
The terminology used when documenting and coding for image lines and samples and detector lines and samples should be well documented and possibly use completely different words. Using the same terms for both is confusing.
We have image lines and samples with some origin (ISIS, center of upper left pixel). What is the upper left? Is it when it is displayed? Not all image display apps put (1,1) in the upper left, some put it in the lower left.
We have detector lines and samples also with some origin, but do not always explicitly indicate which is being used or calculated. Detector elements or pixels (not always CCD) are numbered by the instrument teams and engineers.
If we assume some relationship between the two, that needs to be documented well. Or, we consider using something like what spicelib does with rotations: Here are the rotation values (x,y,z) and here is the order they need to be applied in (3,1,2)

**Comment by jessemapel** [comment]
ALE drivers work in 0 based pixels for both image pixels and detector elements. Conversion to other coordinate systems should be handled in sensor specific properties or formatters. The one exception is the line scan rate uses ISIS 0.5 based lines.
