### ISSUE TITLE
Use units to determine multiplication factor for exposure_duration

### ISSUE THREAD

**Issue by kberryUSGS** [USGS-Astrogeology/ale#117]
Sometimes, `exposure_duration` will come in with units from the PDS label. If they're available, the units could be used to determine how to convert the incoming value to seconds.

**Comment by jessemapel** [comment]
@kberryUSGS This sounds mission/instrument specific. Are there any instruments we support right now that use this?

**Comment by kberryUSGS** [comment]
@jessemapel Yes, but I'm not sure which one(s). Kelvin mentioned that the base PDS driver's `exposure_duration` function needed to account for both when units are present and when they are not because they come in in a different format depending on which is true. (Probably a list vs. a single numerical value.)

**Comment by jessemapel** [comment]
This is done. we account for seconds v milliseconds
