### ISSUE TITLE
Could the default for distortion be "NoDistortion" ? 

### ISSUE THREAD

**Issue by kberryUSGS** [USGS-Astrogeology/ale#118]
Is it possible for a driver to have a distortion model of "none" that doesn't do anything, and would it be possible to make this the default?

**Comment by jessemapel** [comment]
Yes, in USGSCSM, the RADIAL distortion model with all 0 coefficients is equivalent to no distortion.

**Comment by jessemapel** [comment]
We can do something similarly for ISIS with the default CameraDistortionMap and all 0 coefficients

**Comment by thareUSGS** [comment]
It would be nice to have an explicit "none" distortion model flag. Setting all zeros isn't very intuitive.

-Trent

**Comment by jessemapel** [comment]
@thareUSGS We could probably handle that in USGSCSM by just having it convert a `NONE` type distortion model in the ISD to an all 0 radial distortion model in the state.

**Comment by jessemapel** [comment]
See #217 
This adds a new NoDistortion mix-in that does this.
