### ISSUE TITLE
Drivers don't have good error message when provided with the wrong type of input image

### ISSUE THREAD

**Issue by kberryUSGS** [USGS-Astrogeology/ale#120]
If using an ALE ISIS driver by mistake with a PDS label, there isn't an error along the lines of "Input doesn't appear to be an ISIS cube." Instead, there is a stack trace to the first failure to read in a value from the label. Having an error message like the example would be an improvement.

**Comment by jessemapel** [comment]
The new architecture uses smarter selection of the driver to help make this a non-issue. @ALL Is this sufficient or should the drivers themselves have better error messages?

**Comment by kberryUSGS** [comment]
I agree that the originally posted issue will be resolved by the refactor. In the refactored `load`, there should still be some user-visible error message if it fails to create a driver rather than just a stack trace.
