### ISSUE TITLE
Many of the instrument drivers have minimal tests. What should be tested in the drivers?

### ISSUE THREAD

**Issue by scsides** [USGS-Astrogeology/ale#121]
Most of the drivers currently only test that a dictionary was created. This seems like it would pass even if the dict was empty. What should a good driver test contain? #112 has some additional tests

**Comment by jlaura** [comment]
Checkout #86 for a discussion and some initial ideas.

**Comment by jessemapel** [comment]
Solution is on the [wiki][(https://github.com/USGS-Astrogeology/ale/wiki/Testing)
