### ISSUE TITLE
Write new Distortion model mix-ins

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/ale#131]
These need to be able to provide the following:

- USGSCSM distortion model

Current list of distortion models is:

- Radial
- Transverse
- LROC NAC
- Kaguya TC
- Dawn FC

**Comment by kberryUSGS** [comment]
It looks like dawn's ale driver doesn't currently return the distortion model key/values looked for in usgscsm and added at https://github.com/USGS-Astrogeology/usgscsm/pull/231/files, so I added it in the PR for this ticket.
