### ISSUE TITLE
Write new base Driver class

### ISSUE THREAD

**Issue by Kelvinrr** [USGS-Astrogeology/ale#137]
The class should be an ABC that enforces the interface. Existing keys should stay more or less the same unless there is a good reason to change it, new information (like naif keywords) can have their names be set by whoever takes the issue. 

- Get the rotation between two frames for the time range of the image
- Get start and stop time for an image
- Get line and sample counts
- Get the sensor frame ID
- Get the target body frame ID
- Get the frame chain between two frames and the frame types for all returned frames
- Get sensor type
- Get sensor name
- Get sensor platform
- Get line scan rates
    - Three lists: Line starts, start time, scan rate
- Get sample summing
- Get line summing
- Get starting detector sample
- Get starting detector line
- Get ISIS NAIFKeywords
    - Return dictionary of keywords and values/lists of values
- Get sensor model version
- Get focal length
- Get the detector to focal plane transformations
- Get the target body radii
- Get the detector center
- Get the USGSCSM distortion model

**Comment by jlaura** [comment]
Closed by #163
