### ISSUE TITLE
Add CommonNaifKeywords to SPICE mix-in

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/ale#158]
This should return all a dictionary of all of the NAIF Keywords cached by the Spice, Sensor, and Camera classes in ISIS. This method will then be called by the concrete drivers and they will append sensor specific NAIF Keyword to the dictionary.

**Comment by SgStapleton** [comment]
Looks like these values are going to be sensor specific anyhow. Here is an example from Cassini:

Object = NaifKeywords
  BODY606_RADII                    = (2575.0, 2575.0, 2575.0)
  BODY_FRAME_CODE                  = 10044
  CLOCK_ET_-82_1514302573_COMPUTED = 675c871e3684a641
  CLOCK_ET_-82_1514302920_COMPUTED = c93886d43884a641
  INS-82371_TRANSX                 = (0.0, 1.0, 0.0)
  INS-82371_TRANSY                 = (0.0, 0.0, 1.0)
  INS-82371_ITRANSS                = (0.0, 1.0, 0.0)
  INS-82371_ITRANSL                = (0.0, 0.0, 1.0)
End_Object


After confirming with a couple missions' spiceinit'd cubes, it appears that there are not really any common keywords between them. This does not appear to be a useful addition to the SPICE class. @jessemapel Is this issue good to close, you think?

**Comment by jessemapel** [comment]
I know that the `BODY*_RADII` and `BODY_FRAME_CODE` keywords at least are shared. These are added by the base camera classes in ISIS.

**Comment by SgStapleton** [comment]
Another example:

Object = NaifKeywords
  BODY301_RADII                             = (1737.4, 1737.4, 1737.4)
  BODY_FRAME_CODE                           = 31001
  INS-85626_SWAP_OBSERVER_TARGET            = TRUE
  INS-85626_LIGHTTIME_CORRECTION            = NONE
  INS-85626_LT_SURFACE_CORRECT              = TRUE
  INS-85626_FOCAL_LENGTH                    = 4.693
  INS-85626_PIXEL_PITCH                     = 0.009
  CLOCK_ET_-85_1/274692469:15073_COMPUTED   = 8d506af75541b241
  INS-85626_FILTER_BANDCENTER_SIZE_COMPUTED = 2
  INS-85626_FILTER_BANDCENTER               = (321, 360)
  INS-85626_FILTER_OFFSET_SIZE_COMPUTED     = 2
  INS-85626_FILTER_OFFSET                   = (244, 302)
  INS-85626_FILTER_BANDID_SIZE_COMPUTED     = 2
  INS-85626_FILTER_BANDID                   = (1, 2)
  INS-85641_FOCAL_LENGTH                    = 4.6690884
  INS-85641_BORESIGHT_SAMPLE                = 513.5482
  INS-85641_BORESIGHT_LINE                  = 295.4784
  INS-85642_FOCAL_LENGTH                    = 4.7120818
  INS-85642_BORESIGHT_SAMPLE                = 513.5601
  INS-85642_BORESIGHT_LINE                  = 295.4764
  INS-85626_COLOR_SAMPLE_OFFSET             = 264
  INS-85626_TRANSX                          = (0.0, 0.0, -0.009)
  INS-85626_TRANSY                          = (0.0, 0.009, 0.0)
  INS-85626_ITRANSS                         = (0.0, 0.0, 111.11111111111)
  INS-85626_ITRANSL                         = (0.0, -111.11111111111, 0.0)
  INS-85626_OD_K                            = (-0.024, -7.0e-04, -7.0e-04)
  INS-85641_TRANSX                          = (0.0, 3.11994535e-07,
                                               -0.008999999994592)
  INS-85641_TRANSY                          = (0.0, 0.008999999994592,
                                               3.11994535e-07)
  INS-85641_ITRANSS                         = (0.0, -0.0038517843825,
                                               111.11111104435)
  INS-85641_ITRANSL                         = (0.0, -111.11111104435,
                                               -0.0038517843825)
  INS-85641_OD_K                            = (0.025824582751555,
                                               4.66139483592234e-05,
                                               1.44650735580122e-04)
  INS-85642_TRANSX                          = (0.0, 1.425859353e-06,
                                               -0.008999999887051)
  INS-85642_TRANSY                          = (0.0, 0.008999999887051,
                                               1.425859353e-06)
  INS-85642_ITRANSS                         = (0.0, 0.017603201893,
                                               111.11110971668)
  INS-85642_ITRANSL                         = (0.0, -111.11110971668,
                                               0.017603201893)
  INS-85642_OD_K                            = (0.025144400734802,
                                               2.2601061670964e-04,
                                               1.24071862326273e-04)
End_Object

**Comment by jessemapel** [comment]
For clarification, even if the keyword itself contains the instrument ID or the body ID, there will always be a keyword called `BODY<Body ID>_RADII`. We can in the SPICE mix-in substitute in the Body ID and create the keyword, value pair.
