### ISSUE TITLE
Method overrides in SimpleSpice

### ISSUE THREAD

**Issue by SgStapleton** [USGS-Astrogeology/ale#160]
The SimpleSpice Class in conftest.py makes use of the np.ones() method in many of its method overrides, but testing would benefit from returning a sequence of numbers rather than a list of just ones. For example, for the NaifData semimajor and semiminor methods, there is no way to confirm the proper value is being returned.

**Comment by SgStapleton** [comment]
Consider using np.linsapce() instead?

**Comment by jlaura** [comment]
`np.arange(<n-numbers>)` is probably what you want.

https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html

**Comment by jessemapel** [comment]
We no longer use simple spice so this is no longer relevant.
