### ISSUE TITLE
Update SPICE mix-in to use new transformation object

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/ale#164]
This is a follow on to #128. The SPICE mix-in needs to properly return the frame tree. Until we have access to the low level NAIF routines to construct the frame chain, the SPICE mix-in will construct the following tree:

```
          J2000
         /     \
        /       \
   Spacecraft    \
      /           \
     /             \
    /               \
Sensor          Target Body
```

**Comment by jlaura** [comment]
Now that #162 is merged, it should be possible to get this implemented cleanly.
