### ISSUE TITLE
Make JSON input for initial draft of eal library

### ISSUE THREAD

**Issue by kberryUSGS** [USGS-Astrogeology/ale#24]

**Comment by kberryUSGS** [comment]
This can be taken out of an existing ISD file for MDIS -- everything related to the position/velocity of the body and target and sun.

**Comment by SgStapleton** [comment]
Any suggestions on a name for this file...?

**Comment by acpaquette** [comment]
@kberryUSGS If you know where, could you point to where the existing ISD files for MDIS are?

**Comment by jessemapel** [comment]
See #138 and #139 for examples
