### ISSUE TITLE
naif_keywords needs to properly reflect keyword used to acquire values 

### ISSUE THREAD

**Issue by Kelvinrr** [USGS-Astrogeology/ale#268]
Naif_Keywords group in the ISIS Ale ISD currently returns a fixed set of keys. Sometimes this doesn't reflect what was actually used in the spice calls (i.e. MDIS kernels have the pixel size as `pixel_pitch` but it is still stored under `pixel_size` in naif keywords). If we wanted to override naif_keywrods to reflect this, we would have to overwrite in every MDIS driver.  We should probably consider a cleaner way to handle naif_keywords. Seems something that can be fairly programmatic since that information is already embedded in Spice based overrides.

**Comment by jessemapel** [comment]
This is fixed by our current sledgehammer approach.
