### ISSUE TITLE
How do we interface the python code with the c++ code?

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/ale#28]
We are going to be called python functions from c++ and need to determine how we want to do this.

**Comment by jessemapel** [comment]
The simplest option is the Python C API

**Comment by jessemapel** [comment]
Another option is Boost Python

**Comment by jessemapel** [comment]
Third option that's based on Boost Python but doesn't require all of boost

[pybind11](https://github.com/pybind/pybind11)

[Calling python from c++](https://pybind11.readthedocs.io/en/master/advanced/pycpp/index.html)

**Comment by SgStapleton** [comment]
Do you think Python C API is going to be simpler than pybind11?

**Comment by jessemapel** [comment]
As long as our interface point is just passing strings, then the C API is probably simpler. If our interface becomes more complex, then the C API may be cumbersome.

**Comment by kberryUSGS** [comment]
Since I'm not sure this is written down anywhere(?), did we decide to pass around strings containing the json representation of the position/pointing information between python and c++?

**Comment by Kelvinrr** [comment]
This should be covered with #64. I believe using the c-api is good enough for now. If the interaction between C++ and Python ever gets more complex, we should definitely punt to a third party library that makes calling python from C++ cleaner to work with.

**Comment by Kelvinrr** [comment]
This should be taken cared of with #64. As long as the interaction between python and C++ is only happening through one function, I think the Python C API is good enough.
