### ISSUE TITLE
Colliding Naif Keywords

### ISSUE THREAD

**Issue by acpaquette** [USGS-Astrogeology/ale#323]
Currently in ALE we are doing a mass search for anything containing the ikid, along with the target_id from the kernel pool. To get some of the drivers working in ISIS we also need to search for the any naif keywords containing the fikid from the kernel pool.

The way we are searching for this right now will get duplicate keywords and put those keywords into a dictionary. One of those keywords is then compared to the truth data and if the wrong keyword was obtained then certain tests will fail. To fix this we need to search for keywords in the kernel pool with respect to how the keywords were loaded. I believe this can be done using gdpool or other spice functions for searching the pool. Right now we are using gnpool which doesn't seem to respect kernel loading order.

This is needs to be addressed in #321 so it can be merged.

**Comment by Kelvinrr** [comment]
Do you have a list of instruments/drivers where this happens?

**Comment by Kelvinrr** [comment]
addressed by #326 

Addendum kernels are sorted to the back of the kernel list.
