### ISSUE TITLE
MGS Driver does not account for TimeBias

### ISSUE THREAD

**Issue by acpaquette** [USGS-Astrogeology/ale#389]
In working on ckwriter tests for ISIS I ran into an ISIS camera feature that was not accounted for in the MGS driver. 

There is a time bias offset being applied to both `MocNA` and `MocWA` instrument rotation of -1.15 that was not accounted for in the MGS driver. The MGS driver also seems to be missing from ALE, but has existed at one point as we have three mgs isds in the ISIS gtest data area under the `ThreeImageNetwork`.

This is going to impact the ISIS testing sprint as it is enough of an offset to likely change the truth data for many tests that use the `ThreeImageNetwork`

**Comment by jessemapel** [comment]
Here's the reference from ISIS https://github.com/USGS-Astrogeology/ISIS3/blob/dev/isis/src/mgs/objs/MocNarrowAngleCamera/MocNarrowAngleCamera.cpp#L55

We can add this into the driver fairly easily, how big of an impact on the ISIS testing do we expect from this? The ISDs used there are already "Fake" data so does it matter if they are missing this time bias?

**Comment by acpaquette** [comment]
Looks like this is actually just an issue in ISIS. Specifically how the MOC NA/WA cameras interact with ckwriter
