### ISSUE TITLE
Incomplete Loads Parameter Passing

### ISSUE THREAD

**Issue by acpaquette** [USGS-Astrogeology/ale#394]
The python binding code to call the python loads function from ALE is not passing the verbose flag correctly to the python function. 

Currently it looks like the binding function is only wrapping three arguments where it needs to be wrapping all four.

The binding function just needs to be updated to handle the extra argument.

**Comment by AustinSanders** [comment]
@acpaquette Has this been addressed?  I thought I remembered seeing this / using the verbose flag

**Comment by jessemapel** [comment]
Done in #431
