### ISSUE TITLE
ALE - now getting 'No Such Driver for Label' for previously supported cub

### ISSUE THREAD

**Issue by thareUSGS** [USGS-Astrogeology/ale#398]
All,
  I have brand new (clean) ALE environment using `conda install -c conda-forge ale`

When I run on a HiRISE cube (that previously worked), I am now getting a 'No Such Driver for Label' . This file currently sits in
/scratch/thare/ale/

```
import ale
import json
import os

cub_loc1="ESP_011969_1425_REDmos_hijitreged.balance.noproj.8bit.cub"
usgscsm_str1 = ale.loads(cub_loc1)
```

Here is the error:
  File "/scratch/thare/ale/run_ALE.py", line 10, in <module>
    usgscsm_str1 = ale.loads(cub_loc1)
  File "/home/thare/.conda/envs/ale/lib/python3.9/site-packages/ale/drivers/__init__.py", line 145, in loads
    res = load(label, props, formatter, verbose=verbose)
  File "/home/thare/.conda/envs/ale/lib/python3.9/site-packages/ale/drivers/__init__.py", line 128, in load
    raise Exception('No Such Driver for Label')
Exception: No Such Driver for Label

**Comment by jessemapel** [comment]
@thareUSGS What versions of ALE did you get, the latest? You can check with `conda list ale`

**Comment by jessemapel** [comment]
Well it looks like scipy changed their rotation class and renamed from_dcm which is causing this issue.

**Comment by jessemapel** [comment]
@thareUSGS For right now, I was able to work around this issue by installing scipy1.5.3, it seems the latest 1.6.0 release broke us. Run

`conda install -c conda-forge scipy=1.5.3`

and you should be good to go, I was able to generate the appropriate ISD that way.

**Comment by thareUSGS** [comment]
Tested and it seems to be working - thanks!

So the current installation would need to be.

```
conda create -n ale
conda activate ale
conda install -c conda-forge ale
 # to fix an issue in scipy, need to role back
conda install -c conda-forge scipy=1.5.3
```

and just for the post I ran these cubes using the commands
```
import ale
import json
import os
cub_loc1="ESP_011969_1425_REDmos_hijitreged.balance.noproj.8bit.cub"

usgscsm_str1 = ale.loads(cub_loc1)
csm_isd1 = os.path.splitext(cub_loc1)[0] + '.json'
 with open(csm_isd1, 'w') as isd_file:
    isd_file.write(usgscsm_str1)
```

**Comment by jessemapel** [comment]
Thanks for getting back on this Trent. I'm going to re-open this until my PR gets merged because this is still an issue.

I am also going to push a patch to the ALE feedstock the automatically restricts scipy to be <= 1.5.3. That should prevent the need for manually downgrading scipy. I'll post over here once that's done.

**Comment by jessemapel** [comment]
Okay this is all done now. The PR for the next release is in and I tested it over there and it works. I also have updated the ale-feedstock so that 0.8.5 build 2 not imposes scipy < 1.6.0 and in my testing it works with that package.
