### ISSUE TITLE
Command line .json generator from .cub files?

### ISSUE THREAD

**Issue by rbeyer** [USGS-Astrogeology/ale#436]
I notice that there isn't a command-line script to generate .json ISD files from a spiceinit'd cube.

In order to use CSM with ASP, that is an important "conversion" step, and we instruct our users to write a little Python program, but I was thinking maybe the right thing to do is PR something like that to this repo so there is an `ale_translate` (to echo gdal) or an `isd_generate` command line program (I'm rotten with names, please suggest one you like) that would be present when folks installed *ale*.

If that's something you're looking for in this repo, I will submit a PR.

**Comment by jessemapel** [comment]
Adding an entry point to do this sounds like a good enhancement. A PR would be very welcome.

**Comment by AustinSanders** [comment]
Closed as of #437
