### ISSUE TITLE
Domain Review

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/ale#441]
This issue is for the Domain Review step of the USGS release process. More information can be found on the [USGS Software Management Website](https://www.usgs.gov/software-management/types-software-review).

**Comment by jessemapel** [comment]
@thareUSGS Please respond in a comment on here with the results of the review.

**Comment by thareUSGS** [comment]
A domain review has been conducted on this software the week of 03/25/22.

ALE is a library to support metadata (SPICE or spacecraft pointing) for individual images in support of camera models as used by [usgscsm](https://github.com/USGS-Astrogeology/usgscsm) library. The use of ALE and usgscsm library has been tested, using _knoten_ (currently internal to USGS), against the camera models under the well-establish ISIS photogrammetry suite. A table of comparisons between ALE/usgscsm's output and ISIS's output can be found at the USGS Gitlab _knoten_ site and the Jupyter notebooks used to generate those results.

Beyond the well documented code, ALE consists of a suite for regression testing and example Jupyter notebooks to show how it is used. I will submit a pull request to update minor spelling issues (mostly in the code comments).

Based on the results of the comparison, this software passes domain review.

**Comment by thareUSGS** [comment]
pull request from branch is now available for review: https://github.com/USGS-Astrogeology/ale/pull/445

**Comment by jessemapel** [comment]
@thareUSGS Thank you very much!
