### ISSUE TITLE
LRO MiniRF always inherits ISISLabel, even if EDR

### ISSUE THREAD

**Issue by ladoramkershner** [USGS-Astrogeology/ale#459]
I noticed the LRO MiniRF driver inherits from:
Radar
NaifSpice
IsisLabel
Driver

What happens when we are ingesting a raw mission EDR label? Should we add IsisPDS3 to the definition of the driver (and then eventually PDS4), or would this cause possible confusion in overwriting certain functions?

I also suspect that this question could apply to more than just eh MiniRF driver..

**Comment by jessemapel** [comment]
The LRO MiniRF driver is only designed to work with ISIS Cubes, hence it uses the ISISLabel mix-in. It's not intended to be used with PDS labels, so it doesn't need any PDS label mix-ins.
