### ISSUE TITLE
ISIS Dependency

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/ale#497]
When using `util.generate_kernels_from_cub`, the ALE library throws an error if ISISROOT is not set. (I am using this function as a work around to #495.) This seems to indicate that ISIS is a dependency if one is going to be getting kernels from ISIS cubes. Is ISIS a necessary dependency of ALE? If so, can it be added to the environment.yml? If not, is it possible to refactor so that the above utility is usable without setting ISISROOT? Thanks!

**Comment by jessemapel** [comment]
No, adding ISIS as a dependency would be very very bad because ISIS uses ALE. That is purely a helper function that requires your IsisPreferences file, so you need to give it an ISISROOT. It could be modified to check your home directory for an IsisPreferences file.

**Comment by jlaura** [comment]
That all sounds very reasonable. It is not documented anywhere as far as I can see. Am I missing ALE docs perhaps?

**Comment by jessemapel** [comment]
The docs can be found here: https://ale.readthedocs.io/en/latest/library/python/util.html#ale.util.generate_kernels_from_cube

It doesn't appear to document the requirements though.

**Comment by jessemapel** [comment]
I was incorrect, the code already first attempts to find an IsisPreferences file in your home directory.
