### ISSUE TITLE
How do we want to setup our docs?

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/ale#5]

**Comment by kberryUSGS** [comment]
For API docs: Doxygen? Or Doxygen + Sphinx + Breathe?

**Comment by rbeyer** [comment]
Please do something.  The README is almost information-free.  There are no examples (without hunting into the codebase for Jupyter notebooks that may or may not load), and no description of what "ale" actually does, or what someone would use it for.

**Comment by jessemapel** [comment]
This is on the todo list for later this month. Kristin's suggestion from (oh jeeze) almost 2 years ago is the way I want to go on this.

**Comment by rbeyer** [comment]
Oh, BTW, I didn't even *think* to look in the wiki, but there's more documentation over there, that's better than nothing.  At the very least direct people there from the README in the interim.

**Comment by jessemapel** [comment]
Hosted on github pages: https://usgs-astrogeology.github.io/ale/library/python/index.html
