### ISSUE TITLE
Changing default branch from master to main

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/ale#505]
Git has moved away from the master/slave branch naming because it's culturally insensitive. Instead, new git repos now use main as the default branch. This repo still uses the old master primary branch and we should update it to use the new default branch name.

This would be a minor disruption to work.

Open pull requests will need to be changed to pull into main instead. This should not impact contributors; it will be a one time action for maintainers.

Contributors will need to pull and create branches from main instead of master. For example, to create a new branch for work, you will run `git fetch upstream && git checkout -b my_work_branch upstream/main` instead of `git fetch upstream && git checkout -b my_work_branch upstream/master`. To ensure contributors don't accidentally create branches or pull from the now out-of-date master branch, we should delete it. This will result in the old commands erroring instead of silently continuing but not actually pulling the most recent changes.

**Comment by jessemapel** [comment]
I would like to coordinate this work across our public GitHub repos so that everyone can make the same change all at once instead of staggering it and confusing people. See:

https://github.com/USGS-Astrogeology/plio/issues/183

https://github.com/USGS-Astrogeology/knoten/issues/106

https://github.com/USGS-Astrogeology/swigcsm/issues/35

**Comment by jlaura** [comment]
:+1: I support the transition to main as quickly as is reasonable and standardizing on main. We should set all default branches to main. Can we also protect main while we are at it?

**Comment by jlaura** [comment]
Completed 2.23.23. Please update your remotes!
