### ISSUE TITLE
Check the sig figs & accuracy of human-readable json format. 

### ISSUE THREAD

**Issue by kberryUSGS** [USGS-Astrogeology/ale#80]
Stuart brought up that Naif deliberately uses binary for the accuracy. We need to test / check into whether or not we meaningfully lose precision or accuracy by using a non-binary json format.

**Comment by jessemapel** [comment]
We are not seeing significant degredation due to using human readable JSON. We are roughly accurate with in ~12-15 significant figures which is sufficient.

**Comment by jessemapel** [comment]
We are not seeing significant degredation due to using human readable JSON. We are roughly accurate with in ~12-15 significant figures which is sufficient.
