### ISSUE TITLE
ALE dumps JSON to string silently

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/ale#88]
https://github.com/USGS-Astrogeology/ale/blob/master/ale/drivers/__init__.py#L61

This is very non-pythonic to have the library return a serialized string containing JSON. 99.9% of use cases are then going to immediately `json.loads` this so that further processing can occur or `json.dumps` it to a file. I am guessing that the latter use case is the one the linked file is seeking to accommodate, but this looks like strange behavior to a consumer (pfeffernusse in this case).

**Comment by Kelvinrr** [comment]
We need one that returns a string for the C++ interface as it makes things much easier than carrying around a python object. Which is why two exists, one that returns a string and one that returns a dict. Are you suggesting simply renaming the one that returns a string or removing it entirely?

**Comment by jessemapel** [comment]
@jlaura Does Kelvin's comment answer why this is? Do you have a proposed change?

**Comment by jlaura** [comment]
I don't know that we have a clean resolution on this. The loads method returns a string, which is great for the C++ interface, but counter-intuitive to the Python interface. 

Basically, I am suggesting that load/loads should (if we want to follow the python json API) be concerned with whether the input is a string of JSON or a file pointer. The returns are consistent. It is counter-intuitive for someone used to load/loads to have different inputs AND different output types. 

Options I see are: (1) have the return always be a json encoded string, (2) have the return always be JSON and then write another accessor that the C-API is going to use, or (3) as 2, but have the C-API make the dict to str conversion.

**Comment by jessemapel** [comment]
I'm inclined to have these methods always return a JSON object and then have the C API convert it into a string @Kelvinrr how complex is that?

**Comment by Kelvinrr** [comment]
So this is a problem that's been messing with me for a while, seems like the best thing is simply changing the name of the function from load/loads. Making the C-Api make the conversion dict to JSON string is not gonna be worth it, a lot of conversion code involved, our best option is expose a function to C++ that does the conversion for us. #253  makes it so load/loads have the same input but different output (dict and JSON string respectively). Which, as @jlaura points out, is somewhat counter-intuitive to how JSON uses load/loads (I've stared at it for so long it makes perfect sense to me). We could always just rename them to something else if it's an issue.

**Comment by jessemapel** [comment]
Load and load now returns a dictionary and loads convert to a string.
